#ifndef IEVENT_H
#define IEVENT_H

// Base interface for Event classes.
// Events are generated by the application when either:
//      - specific values are read from Physical Components,
//      - the machine receives conditions necessary to generate an Event
class Event
{
};

#endif // IEVENT_H
